### ISSUE TITLE
How to fixed Package Bug

### ISSUE THREAD

**Issue by ghost** [darkapplepower/comcigan#1]
`{"message":"Cannot call property getEncoder in object [JavaPackage java.util.Base64]. It is not a function, it is \"object\".","fileName":"file:/storage/emulated/0/msgbot/global_modules/comci.js","lineNumber":13}
`
getTimeTable() 오류에오, 왜 안대는거죠

**Comment by ghost** [comment]
저런 버그 라벨 안붙었네오

**Comment by darkapplepower** [comment]
안드로이드 버전이 7 이하라서 나는 오류인 거시에요.
android.util.Base64를 사용하도록 하면 저런 현상이 없어지긴 합니다. 수정해둘게요

**Comment by ghost** [comment]
Fixed That Close Issue
